site_name: Doce GSR
site_author: Jurandy Soares
site_url: https://jurandysoares.github.io/doce-gsr/

repo_url: https://github.com/jurandysoares/doce-gsr
edit_uri: edit/main/docs/

theme:
  name: material
  language: pt
  features:
    - content.action.edit
    - content.action.view
